### PR TITLE
Started porting the extension to Gnome 45.

### PR DESCRIPTION
**Pull request by Boria138**
I'm porting according to this guide
https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm Since I am porting for myself and have not written extensions before, I made this pr a draft (I will be glad to have help in editing)

### CODE REVIEW

**Comment by Boria138** [comment]
Since when testing for gnome 45 it turned out that the extension absolutely does not work, I transfer the pr back to the draft status

**Comment by Boria138** [comment]
@LorenzoMorelli Any idea why these errors appeared?

```sh
TypeError: prefsModule.default is not a constructor

Stack trace:
  _loadPrefs@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:33:26
  async*_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:21:14
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:12:4
  OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:139:33
  async*_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
  _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  ```
  
  ```Unknown module: 'lib/Utility.js'```
  
The first error occurs when trying to open the settings 
The second one does not allow you to enable the extension

**Comment by LorenzoMorelli** [comment]
Hi, I think it could be due to the gnome 45 new way for importing libraries

**Comment by Boria138** [comment]
> Hi, I think it could be due to the gnome 45 new way for importing libraries

Yes indeed the paths have changed, now quicksettings contains quicksettingsmenu so nothing works

**Comment by Boria138** [comment]
@LorenzoMorelli I have completely translated the settings page to 45 gnome, but to overcome the error ```ambiguous indirect export: AttachedToBatteryView``` still does not come out, it is not known what the problem is because I have not found any errors after reading the documentation.

**Comment by LorenzoMorelli** [comment]
Hi @Boria138, First of all thank you for your work. Currently I don't have a Gnome 45 machine. I'm going to set it up and consequently try and test your work. I don't know if you were able to solve the `ambiguous indirect export: AttachedToBatteryView`. If everything works well, I'm going to create a new release with this porting

**Comment by Boria138** [comment]
> Hi @Boria138, First of all thank you for your work. Currently I don't have a Gnome 45 machine. I'm going to set it up and consequently try and test your work. I don't know if you were able to solve the `ambiguous indirect export: AttachedToBatteryView`. If everything works well, I'm going to create a new release with this porting

Unfortunately all I had time to move is the settings page, then I was too busy, so the extension does not work in terms of functionality just open the settings

**Comment by LorenzoMorelli** [comment]
I started working on it today. I was able to solve the problem you mentioned, but there are still some parts missing in the porting. Let's see how long it's gonna take since I'm also quite busy at the moment :)

**Pull request merged**
